[project]
name = "TahubuSF"
version = "0.1.0"
description = "TahubuSF is a tool for managing Sitefinity AI Applications"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.8.0",
    "asyncio>=3.4.3",
]
